[project]
name = "speed-bridge"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.bridge-guardian]
path = "contracts/bridge-guardian.clar"
depends_on = []

[contracts.transaction-logger]
path = "contracts/transaction-logger.clar"
depends_on = []

[contracts.token-translator]
path = "contracts/token-translator.clar"
depends_on = []

[contracts.bridge-registry]
path = "contracts/bridge-registry.clar"
depends_on = []

[contracts.cross-chain-sync]
path = "contracts/cross-chain-sync.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
